# Generated by Django 6.0.4 on 2026-04-12 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='birth_latitide',
            new_name='birth_latitude',
        ),
    ]
