# Generated by Django 6.0.4 on 2026-05-04 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Panchang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('data', models.JSONField()),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BSCalendarData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bs_year', models.IntegerField()),
                ('bs_month', models.IntegerField()),
                ('num_days', models.IntegerField()),
                ('start_day_of_week', models.IntegerField()),
                ('ad_month_start', models.DateField()),
            ],
            options={
                'ordering': ['bs_year', 'bs_month'],
                'indexes': [models.Index(fields=['bs_year', 'bs_month'], name='astrology_b_bs_year_af3a48_idx')],
                'unique_together': {('bs_year', 'bs_month')},
            },
        ),
        migrations.CreateModel(
            name='Festival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bs_date', models.CharField(max_length=20)),
                ('ad_date', models.DateField()),
                ('name_english', models.CharField(max_length=200)),
                ('name_nepali', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('significance', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('festival', 'Festival'), ('religious', 'Religious'), ('national', 'National'), ('seasonal', 'Seasonal')], default='festival', max_length=50)),
                ('year', models.IntegerField()),
            ],
            options={
                'ordering': ['bs_date'],
                'indexes': [models.Index(fields=['ad_date'], name='astrology_f_ad_date_9ff937_idx'), models.Index(fields=['bs_date'], name='astrology_f_bs_date_14cf31_idx')],
                'unique_together': {('bs_date', 'ad_date')},
            },
        ),
        migrations.CreateModel(
            name='Horoscope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rashi', models.CharField(choices=[('aries', 'मेष'), ('taurus', 'वृषभ'), ('gemini', 'मिथुन'), ('cancer', 'कर्क'), ('leo', 'सिंह'), ('virgo', 'कन्या'), ('libra', 'तुला'), ('scorpio', 'वृश्चिक'), ('sagittarius', 'धनु'), ('capricorn', 'मकर'), ('aquarius', 'कुम्भ'), ('pisces', 'मीन')], max_length=20)),
                ('horoscope_type', models.CharField(choices=[('daily', 'Daily')], default='daily', max_length=20)),
                ('date', models.DateField()),
                ('prediction', models.TextField()),
                ('love_score', models.IntegerField(default=3)),
                ('career_score', models.IntegerField(default=3)),
                ('health_score', models.IntegerField(default=3)),
                ('money_score', models.IntegerField(default=3)),
                ('lucky_color', models.CharField(blank=True, max_length=50)),
                ('lucky_number', models.IntegerField(blank=True, null=True)),
                ('lucky_time', models.CharField(blank=True, max_length=50)),
                ('advice', models.TextField(blank=True)),
                ('api_response', models.JSONField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', 'rashi'],
                'indexes': [models.Index(fields=['rashi', 'date'], name='astrology_h_rashi_ba7855_idx'), models.Index(fields=['date'], name='astrology_h_date_64ae16_idx')],
                'unique_together': {('rashi', 'horoscope_type', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Kundali',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart_data', models.JSONField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
            ],
        ),
    ]
