# Generated by Django 6.0.4 on 2026-04-12 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astrology', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Panchanga',
            new_name='Panchang',
        ),
    ]
