# Generated by Django 6.0.4 on 2026-04-26 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrology', '0002_rename_panchanga_panchang'),
    ]

    operations = [
        migrations.CreateModel(
            name='BSCalendarData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bs_year', models.IntegerField()),
                ('bs_month', models.IntegerField()),
                ('num_days', models.IntegerField()),
                ('start_day_of_week', models.IntegerField()),
                ('ad_month_start', models.DateField()),
            ],
            options={
                'ordering': ['bs_year', 'bs_month'],
                'indexes': [models.Index(fields=['bs_year', 'bs_month'], name='astrology_b_bs_year_af3a48_idx')],
                'unique_together': {('bs_year', 'bs_month')},
            },
        ),
        migrations.CreateModel(
            name='Festival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bs_date', models.CharField(max_length=20)),
                ('ad_date', models.DateField()),
                ('name_english', models.CharField(max_length=200)),
                ('name_nepali', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('significance', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('festival', 'Festival'), ('religious', 'Religious'), ('national', 'National'), ('seasonal', 'Seasonal')], default='festival', max_length=50)),
                ('year', models.IntegerField()),
            ],
            options={
                'ordering': ['bs_date'],
                'indexes': [models.Index(fields=['ad_date'], name='astrology_f_ad_date_9ff937_idx'), models.Index(fields=['bs_date'], name='astrology_f_bs_date_14cf31_idx')],
                'unique_together': {('bs_date', 'ad_date')},
            },
        ),
    ]
