# Generated by Django 6.0.4 on 2026-04-28 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrology', '0003_bscalendardata_festival'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horoscope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rashi', models.CharField(choices=[('aries', 'मेष'), ('taurus', 'वृषभ'), ('gemini', 'मिथुन'), ('cancer', 'कर्क'), ('leo', 'सिंह'), ('virgo', 'कन्या'), ('libra', 'तुला'), ('scorpio', 'वृश्चिक'), ('sagittarius', 'धनु'), ('capricorn', 'मकर'), ('aquarius', 'कुम्भ'), ('pisces', 'मीन')], max_length=20)),
                ('horoscope_type', models.CharField(choices=[('daily', 'Daily'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='daily', max_length=20)),
                ('date', models.DateField()),
                ('prediction', models.TextField()),
                ('love_score', models.IntegerField(default=3)),
                ('career_score', models.IntegerField(default=3)),
                ('health_score', models.IntegerField(default=3)),
                ('money_score', models.IntegerField(default=3)),
                ('lucky_color', models.CharField(blank=True, max_length=50)),
                ('lucky_number', models.IntegerField(blank=True, null=True)),
                ('lucky_time', models.CharField(blank=True, max_length=50)),
                ('advice', models.TextField(blank=True)),
                ('api_response', models.JSONField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', 'rashi'],
                'indexes': [models.Index(fields=['rashi', 'date'], name='astrology_h_rashi_ba7855_idx'), models.Index(fields=['date'], name='astrology_h_date_64ae16_idx')],
                'unique_together': {('rashi', 'horoscope_type', 'date')},
            },
        ),
    ]
