# Generated by Django 6.0.4 on 2026-05-02 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrology', '0004_horoscope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horoscope',
            name='horoscope_type',
            field=models.CharField(choices=[('daily', 'Daily')], default='daily', max_length=20),
        ),
    ]
