# Generated by Django 6.0.4 on 2026-05-21 08:52

import rituals.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='file',
            field=models.FileField(storage=rituals.storage.PDFCloudinaryStorage(), upload_to='books/pdfs/'),
        ),
    ]
