# Generated by Django 6.0.4 on 2026-05-04 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mantra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('meaning', models.TextField(blank=True)),
                ('audio', models.FileField(blank=True, null=True, upload_to='mantras/audio/')),
                ('language', models.CharField(blank=True, default='Sanskrit', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ritual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('steps', models.JSONField()),
                ('required_items', models.JSONField()),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('mantras', models.ManyToManyField(blank=True, to='rituals.mantra')),
            ],
        ),
    ]
