# Generated by Django 6.0.4 on 2026-05-20 09:07

import rituals.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rituals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantra',
            name='audio',
            field=models.FileField(blank=True, null=True, storage=rituals.storage.AudioCloudinaryStorage(), upload_to='mantras/audio/'),
        ),
    ]
